[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && npm start"
